name: lerna-publish
on: [workflow_dispatch]
jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: npm i -g yarn
      - run: yarn
      - run: ls -la
      - run: npm -v && yarn -v && node -v && lerna -v
      - run: yarn pub