name: Publish packages

on:
  workflow_dispatch:
    branches: [main]

jobs:
  publish-packages:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'yarn'

      - name: Configure git user
        run: |
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
          cat ~/.gitconfig

      - name: Authenticate with registry
        run: |
          echo "registry=https://registry.npmjs.org/" >> .npmrc
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
          npm whoami
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Install dependencies
        run: |
          npm i -g yarn
          yarn
          ls -la
          npm -v
          yarn -v
          node -v
          lerna -v

      - name: Build all packages before tests
        run: yarn build

      - name: Run tests
        run: yarn test

      - name: Publish with lerna
        run: lerna publish --bump=patch --yes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_PAT }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_PAT }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}