name: On pull request
on: [ push ]
jobs:
  checkout:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      - run: ls -la

  setup-workspace:
    needs: checkout
    uses: gstatem/gstatem/.github/workflows/setup.yml@setup-pr-workflow

  on-pull-request:
    needs: setup-workspace
    runs-on: ubuntu-20.04
    steps:
      - name: Run tests
        run: yarn test