name: On pull request
on: [ push ]
jobs:
  on-pull-request:
    runs-on: ubuntu-20.04
    steps:
      - name: Setup workspace
        uses: gstatem/gstatem/.github/workflows/setup.yml@setup-pr-workflow

      - name: Run tests
        run: yarn test