name: Tests

on:
  push:
    branches: [main, improve-workflows]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'yarn'

      - name: Install dependencies
        run: |
          npm i -g yarn
          yarn
          ls -la
          npm -v
          yarn -v
          node -v

      - name: Build all packages
        run: yarn build

      - name: Run tests
        run: yarn test

  tests:
    runs-on: ubuntu-20.04
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'yarn'

      - name: Run tests
        run: yarn test